

Client 

UPLOAD_SYNTAX = "UPLOAD: [a-zA-Z0-9_.]*\nDATA: .*\n\n"
UPDATE_REGEX = "UPDATE: [a-zA-Z0-9_.]*\nDATA: .*\n\n"
UPDATE_HEADER = "UPDATE: %s\nDATA: %s\n\n"
DOWNLOAD_REGEX = "DOWNLOAD: [a-zA-Z0-9_.]*\n\n"

LOCK_RESPONSE ="UNSUCESSSFUL FILE: %s CONTENT: %s\n\n"
UNLOCK_RESPONSE ="SUCESSSFUL UNLOCK FILE: %s \n\n"
LOCK_FAIL ="UNSUCESSSFUL LOCK FILE: %s\n\n"
UNLOCK_FAIL ="UNSUCESSSFUL UNLOCK FILE: %s\n\n"
